# Use Python base image
FROM python:3.9-slim

# Set working directory
WORKDIR /app

# Copy your Python scripts
COPY helpers/ /app/helpers/
COPY __main__.py /app/

# Install required packages
RUN pip install pydicom

# Create directories for input and output
RUN mkdir -p /app/data/input
RUN mkdir -p /app/data/output

# Set environment variables for volumes
ENV INPUT_DIR=/app/data/input
ENV OUTPUT_DIR=/app/data/output

# Run the script
CMD ["python", "__main__.py"]