services:
  orthanc_server:
    container_name: orthanc
    image: jodogne/orthanc-plugins
    ports:
      - 8042:8042
      - 4242:4242
    volumes:
      - ./orthanc.json:/etc/orthanc/orthanc.json:ro
      - ./orthanc_db:/var/lib/orthanc/db/
    restart: always
    networks:
      - pacs

  ohif_viewer:
    container_name: ohif
    image: ohif/app
    ports:
      - 3000:80
    environment:
      - APP_CONFIG:/usr/share/nginx/html/app-config.js
    volumes:
      - ./nginx_ohif.conf:/etc/nginx/conf.d/default.conf:ro
      - ./ohif.js:/usr/share/nginx/html/app-config.js:ro
      - ./Materials/logo.png:/usr/share/nginx/html/logo.png
    restart: always
    networks:
      - pacs
  
  dicom_anonymizer:
    container_name: anonymization
    build:
      context: ./AnonymizationMechanism
      dockerfile: Dockerfile
    volumes:
      - "${INPUT_FOLDER:?Input folder not set}:/app/data/input"  # Original DICOM input
      - "${ANONYMIZED_FOLDER:?Anonymized folder not set}:/app/data/output"  # Anonymized output to local directory
    networks:
      - pacs
    restart: "no"
    environment:
      - INPUT_DIR=/app/data/input
      - OUTPUT_DIR=/app/data/output

  zone_segmentation:
    container_name: zone_segment
    build:
      context: .
      dockerfile: Dockerfile.segment
    env_file:
      - orthanc.env
    volumes:
      - "${ANONYMIZED_FOLDER:?Anonymized folder not set}:/Pats"  # Use anonymized folder as input
      - "${OUTPUT_FOLDER:?Output folder not set}:/Outputs"  # Output segments in NIfTI format
      - "${DICOM_OUTPUT_FOLDER:?DICOM output folder not set}:/dicom_outputs"  # Converted DICOM files
    networks:
      - pacs
  
  visualization:
    container_name: visualization
    image: dimzaridis/vis:0.1
    ports:
      - "8050:8050"
    volumes:
      - "${OUTPUT_FOLDER}:/data"
    environment:
      - OUTPUT_DIR=/data
    networks:
      - pacs
    depends_on:
      - zone_segmentation
    restart: unless-stopped

networks:
  pacs: