# REF: https://github.com/hyper4saken/ohif-orthanc
version: '3.8'
services:
  orthanc_server:
    container_name: orthanc
    # still no luck :-(
    # image: orthancteam/orthanc:22.6.1 
    image: jodogne/orthanc-plugins
    ports:
      - 8042:8042
      - 4242:4242
    volumes:
      - ./orthanc.json:/etc/orthanc/orthanc.json:ro
      - ./orthanc_db:/var/lib/orthanc/db/
    restart: always
    networks:
      - pacs

  ohif_viewer:
    container_name: ohif
    image: ohif/app
    ports:
      - 3000:80
    environment:
      - APP_CONFIG:/usr/share/nginx/html/app-config.js
    volumes:
      - ./nginx_ohif.conf:/etc/nginx/conf.d/default.conf:ro
      - ./ohif.js:/usr/share/nginx/html/app-config.js:ro
      - ./Materials/logo.png:/usr/share/nginx/html/logo.png:ro
    restart: always
    networks:
      - pacs

  zone_segmentation:
    container_name: zone_segment
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
    - orthanc.env
    volumes:
      - ./Pats:/Pats  # Input NIfTI files directory
      - ./Outputs:/Outputs  # Output segments in NIfTI format
      - ./dicom_outputs:/dicom_outputs  # Converted DICOM files
    networks:
      - pacs

networks:
  pacs:
    driver: bridge

volumes:
  orthanc_db:
